---
title: Data provider country statistics
date: "`r Sys.Date()`"
author: Pieter Provoost
output: (function(...) {
  rmdformats::robobook(toc_depth = 4, pandoc_args = c("+RTS", "-K2000m", "-RTS"), ...) })
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })  
---

## New OBIS datasets since 2021

### Config

```{r message=FALSE, warning=FALSE}
start_year <- 2021
end_year <- 2024
```

### Dependencies

```{r message=FALSE, warning=FALSE}
library(DBI)
library(dplyr)
library(glue)
library(countrycode)
library(ggplot2)
```

### Load data

```{r message=FALSE, warning=FALSE}
readRenviron("env.txt")

con <- dbConnect(RPostgres::Postgres(), dbname = Sys.getenv("OBIS_DB"), host = Sys.getenv("OBIS_HOST"), port = Sys.getenv("OBIS_PORT"), user = Sys.getenv("OBIS_USER"), password = Sys.getenv("OBIS_PASSWORD"), bigint = "integer")

res <- dbSendQuery(con, glue("
    select
    	datasets.id,
    	datasets.url,
    	(datasets.statistics->>'Occurrence')::int as records,
    	extract('year' from datasets.created) as year,
    	persons.organization,
    	persons.country as person_country,
    	ih.country as inst_country,
    	persons.oceanexpert_institution_id
    from datasets
    left join metadata.lnk_dataset_person ldp on ldp.dataset_id = datasets.id
    left join metadata.persons on ldp.person_id = persons.id
    left join metadata.institution_hierarchy ih on ih.id = persons.oceanexpert_institution_id
    order by (datasets.statistics->>'Occurrence')::int desc nulls last, datasets.id
"))
datasets <- dbFetch(res) %>%
  mutate(inst_country = stringr::str_replace(inst_country, "Réunion", "France")) %>%
  mutate(inst_country = stringr::str_replace(inst_country, "Wallis Futuna Islands", "Wallis and Futuna Islands")) %>%
  distinct()
```

### Cleanup country names

```{r message=FALSE, warning=FALSE}
country_codes <- countrycode::codelist %>% select(name = un.name.en, iso2c) %>%
  filter(!is.na(iso2c))

datasets <- datasets %>%
  left_join(country_codes, by = c("person_country" = "iso2c")) %>%
  rowwise() %>%
  mutate(country = ifelse(!is.na(inst_country), inst_country, name)) %>%
  mutate(across(where(is.character), ~na_if(., ""))) %>%
  filter(!is.na(country))

head(datasets)
```

### Add region info

```{r message=FALSE, warning=FALSE}
countries <- m49::m49_full %>% mutate(country_or_area = stringr::str_replace(country_or_area, "Turkey", "Türkiye")) %>% select(country_or_area, ldc, lldc, sids, developed, developing, region_name) %>%
  mutate(classification = factor(ifelse(sids, "SIDS", ifelse(region_name == "Africa", "Africa", "other")), levels = c("SIDS", "Africa", "other")))

datasets <- datasets %>%
  left_join(countries, by = c("country" = "country_or_area"))
```

### Statistics

```{r message=FALSE, warning=FALSE}
recent_datasets <- datasets %>%
  filter(year >= start_year & year <= end_year)

recent_stats <- recent_datasets %>%
  distinct(id, records, year, country, sids, region_name, classification) %>%
  filter(!is.na(country)) %>%
  group_by(country, year, sids, region_name, classification) %>%
  summarize(datasets = n(), records = sum(records)) %>%
  arrange(desc(records))

head(recent_stats)
```

```{r message=FALSE, warning=FALSE}
write.csv(recent_stats, file = "output/stats.csv", row.names = FALSE)
recent_stats %>%
  relocate(country, year, records) %>% rmarkdown::paged_table(options = list(rows.print = 100))
```

### Visualize

```{r message=FALSE, warning=FALSE, fig.width=12, fig.height=7, dpi=300}
stats_all_years <- recent_stats %>%
  group_by(country) %>%
  summarize(records = sum(records))

recent_stats <- recent_stats %>%
  mutate(country = factor(country, levels = stats_all_years$country[order(stats_all_years$records)]))

ggplot(data = recent_stats) +
  geom_bar(aes(x = country, y = records, fill = classification), stat = "identity") +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("#e9933e", "#f3c654", "#cccccc")) +
  ggtitle("Biodiversity records contributed to OBIS by country") +
  scale_y_continuous(labels = scales::label_comma()) +
  facet_wrap(~year)

ggsave("output/graph_untransformed.png", width = 12, height = 7, dpi = 300, scale = 1.2, bg = "white")

ggplot(data = recent_stats) +
  geom_bar(aes(x = country, y = records, fill = classification), stat = "identity") +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("#e9933e", "#f3c654", "#cccccc")) +
  ggtitle("Biodiversity records contributed to OBIS by country") +
  scale_y_continuous(labels = scales::label_comma(), trans = "log10") +
  facet_wrap(~year)

ggsave("output/graph.png", width = 12, height = 7, dpi = 300, scale = 1.2, bg = "white")
```

### Statistics

Records and datasets per year:

```{r message=FALSE, warning=FALSE}
recent_datasets %>%
  distinct(id, year, records) %>%
  group_by(year) %>%
  summarize(records = sum(records, na.rm = TRUE), datasets = n())
```

Countries per year and classification:

```{r message=FALSE, warning=FALSE}
recent_stats %>%
  group_by(year, classification) %>%
  summarize(records = sum(records, na.rm = TRUE), datasets = n(), countries = length(unique(country)))
```

## All OBIS datasets so far

```{r message=FALSE, warning=FALSE}
stats <- datasets %>%
  distinct(id, records, year, country, sids, region_name, classification) %>%
  filter(!is.na(country)) %>%
  group_by(country, year, sids, region_name, classification) %>%
  summarize(datasets = n(), records = sum(records)) %>%
  arrange(desc(records))

stats %>%
  group_by(country, classification) %>%
  summarize(min_year = min(year)) %>%
  group_by(classification, min_year) %>%
  summarize(countries = n()) %>%
  arrange(classification, !is.na(min_year), min_year) %>%
  group_by(classification) %>%
  mutate(cumulative_countries = cumsum(countries))
```

## BioEco GeoNode monitoring programmes

```{r message=FALSE, warning=FALSE}
layers <- jsonlite::fromJSON("https://geonode.goosocean.org/api/layers/")$objects
stopifnot(nrow(layers) < 1000)
regions <- unlist(layers$regions)
```

Fix region names:

```{r message=FALSE, warning=FALSE}
unique(regions[which(!regions %in% countries$country_or_area)])

regions <- plyr::revalue(regions, c(
  "United Kingdom" = "United Kingdom of Great Britain and Northern Ireland",
  "Scotland" = "United Kingdom of Great Britain and Northern Ireland",
  "Hawaii" = "United States of America",
  "Alaska" = "United States of America",
  "Queensland" = "Australia",
  "Queensland" = "Australia",
  "Newfoundland and Labrador" = "Canada",
  "California" = "United States of America",
  "Turkey" = "Türkiye",
  "Micronesia, Federated States of" = "Micronesia (Federated States of)",
  "Cape Verde" = "Cabo Verde",
  "Faeroe Islands" = "Faroe Islands",
  "Baker Island" = "United States of America",
  "Northwestern Hawaiian Islands" = "United States of America",
  "Howland Island" = "United States of America",
  "Jarvis Islands" = "United States of America",
  "Johnston Atoll" = "United States of America",
  "Kingman Reef" = "United States of America",
  "Micronesia, Federated States of" = "Micronesia (Federated States of)",
  "Midway Islands" = "United States of America",
  "Palmyra Atoll" = "United States of America",
  "Wake Island" = "United States of America",
  "Cape Verde" = "Cabo Verde"
))
```

```{r message=FALSE, warning=FALSE}
bioeco_countries <- countries %>%
  filter(country_or_area %in% regions)

bioeco_countries %>%
  group_by(classification) %>%
  summarize(n())
```
